# These are supported funding model platforms

github: retched
patreon: retched
ko_fi: retched
buy_me_a_coffee: retched
thanks_dev: retched
custom: 'https://cashapp.com/retched', 'https://paypal.me/retched'