name: Bug Report
description: File a bug report. Use this to explain, in detail, that something is going on with the script. (This SHOULD NOT be used to report general ZenCart errors.)
title: "[BUG]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please complete this form in detail with as many details as possible. If you're going to submit screenshots, you can either submit them as comments to the post this form will make or include them in the first form field.
  - type: dropdown
    id: uspsr-version
    attributes:
      label: USPSr Version
      description: What version of our software are you running?
      options:
        - 0.1.0
        - 0.2.0 (Current Version)
        - N/A (pulled straight from main branch)
      default: 1
    validations:
      required: true
  - type: dropdown
    id: zencart-version
    attributes:
      label: ZenCart Version
      description: What version of our ZenCart are you running? If you're running an Older or non-published version, please selected "Older" and describe above.
      multiple: false
      options:
        - 2.1.x
        - 2.0.x
        - 1.5.x
        - Older
      default: 0
    validations:
      required: true
  - type: dropdown
    id: php-version
    attributes:
      label: PHP Version
      description: As a reminder, this script was written with PHP8 in mind. Older versions, especially older than PHP7, is not guaranteed.
      multiple: false
      options:
        - PHP 8.x
        - PHP 7.x
        - Older
      default: 0
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened? Describe the bug in detail
      description: What did you expect to happen? If you're getting visual errors, include a screen shot here. (If you're getting errors from ZenCart, be sure to include those too.)
      placeholder: What's going on?
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant Log Output
      description: Please copy and paste any relevant log output from the ZenCart logs directory. Obfubiscate any directory names if you wish. This will be automatically formatted into code, so no need for backticks.
      render: shell