name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please complete this form in detail with as many details as possible. If you're going to submit screenshots, you can either submit them as comments to the post this form will make or include them in the first form field.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened? Describe the bug in detail
      description: Also tell us, what did you expect to happen? If you're getting visual errors, include a screen shot here.
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: uspsr-version
    attributes:
      label: USPSr Version
      description: What version of our software are you running?
      options:
        - 0.1.0 (Current Version)
        - 0.1.1 (Development)
      default: 0
    validations:
      required: true
  - type: dropdown
    id: zencart-version
    attributes:
      label: ZenCart Version
      multiple: false
      options:
        - 2.1.x
        - 2.0.x
        - 1.5.x
        - Older
      default: 0
      validations:
        required: true
  - type: dropdown
    id: php-version
    attributes:
      label: PHP Version
      multiple: false
      options:
        - PHP 8.x
        - PHP 7.x
        - Older
      default: 0
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant Log Output
      description: Please copy and paste any relevant log output from the ZenCart logs directory. Obfubiscate any directory names if you wish. This will be automatically formatted into code, so no need for backticks.
      render: shell