name: Bug Report
description: File a bug report. Use this to explain, in detail, that something is going on with the script. (This SHOULD NOT be used to report general ZenCart errors.)
title: "[BUG]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please complete this form in detail with as many details as possible. If you're going to submit screenshots, you can either submit them as comments to the post this form will make or include them in the first form field.
  - type: dropdown
    id: uspsr-version
    attributes:
      label: USPSr Version
      description: What version of the module are you running?
      options:
        - 0.1.0
        - 0.2.0
        - 1.0.0
        - 1.1.0
        - 1.1.1 
        - 1.1.2 (Current Version)
        - 0.0.0 (pulled straight from main branch)
      default: 3
    validations:
      required: true
  - type: dropdown
    id: zencart-version
    attributes:
      label: ZenCart Version
      description: What version of ZenCart are you running? If you're running an older or non-published version, please selected "Older/Other" and describe in the "What happened?" section below.
      multiple: false
      options:
        - 2.1.x
        - 2.0.x
        - 1.5.x
        - Older/Other
      default: 0
    validations:
      required: true
  - type: dropdown
    id: php-version
    attributes:
      label: PHP Version
      description: As a reminder, this script was written with PHP 8.x and PHP 7.x in mind. Older versions, especially older than PHP 7.x, are not supported.
      multiple: false
      options:
        - PHP 8.x
        - PHP 7.x
        - Older
      default: 0
    validations:
      required: true
  - type: input
    id: related-thread
    attributes:
      label: Related Thread
      placeholder: Be sure to include the https:// in the front
      description: Is this issued related to a thread/post from the ZenCart forums? If so, link it here.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened? Describe the bug in detail
      description: What did you expect to happen? If you're getting visual errors, include a screen shot here. (If you're getting errors from ZenCart, be sure to include those too.)
      placeholder: What's going on?
    validations:
      required: true
  - type: textarea
    id: zencart-logs
    attributes:
      label: Relevant ZenCart Log Output
      description: Please copy and paste any relevant log output from ZenCart here. This would be the contents of any myDEBUG file that appeared in your logs directory from ZenCart.
      render: shell
  - type: textarea
    id: uspsr-json-logs
    attributes:
      label: Relevant USPS Log Output
      description: Please copy and paste any relevant log output from the USPSr module here. This would be the contents of any log file generated from the module itself. These are normally named SHIP_uspsr_Debug_.
      render: shell