name: Release Checklist
description: A checklist of items to verify before releasing a new version.
title: "[CHECKLIST]: "
labels: ["checklist"]
assignees:
  - retched
body:
  - type: checkboxes
    id: pre-release-checklist
    attributes:
      label: "Pre-Release Verification"
      description: "Version has been tested for each of the following versions/environments:"
      options:
        - label: "Zencart 1.5.5 / PHP 7.1"
        - label: "ZenCart 1.5.6 / PHP 7.3"
        - label: "ZenCart 1.5.7 / PHP 8.0"
        - label: "ZenCart 1.5.8 / PHP 8.0"
        - label: "ZenCart 2.0.1 / PHP 8.3"
        - label: "ZenCart 2.1.0 / PHP 8.4"
        - label: "ZenCart 2.2.0-dev / PHP 8.4"
        - label: "ZenCart 2.1.0 / PHP 8.5"
        - label: "ZenCart 2.2.0-dev / PHP 8.5"
