name: Release Checklist
description: A checklist of items to verify before releasing a new version.
title: "[CHECKLIST]: "
labels: ["checklist"]
assignees:
  - retched
body:
  - type: checkboxes
    id: pre-release-testing
    attributes:
      label: "Pre-Release Testing"
      description: "Version has been tested for each of the following versions/environments:"
      options:
        - label: "Zencart 1.5.5 / PHP 7.1"
        - label: "ZenCart 1.5.6 / PHP 7.3"
        - label: "ZenCart 1.5.7 / PHP 8.0"
        - label: "ZenCart 1.5.8 / PHP 8.0"
        - label: "ZenCart 2.0.1 / PHP 8.3"
        - label: "ZenCart 2.1.0 / PHP 8.4"
        - label: "ZenCart 2.2.0-dev / PHP 8.4"
        - label: "ZenCart 2.1.0 / PHP 8.5"
        - label: "ZenCart 2.2.0-dev / PHP 8.5"
  - type: checkboxes
    id: release-checklist
    attributes:
      label: "Release Checklist"
      description: "Please verify each of the following items have been completed before releasing:"
      options:
        - label: "Update documentation with new version and changes"
        - label: "Checkout a branch with the new version number as the name (ie. v_x.y.z)"
        - label: "Update version number in all file headers and the encapsulated installer"
        - label: "Rename the version folder in zc_plugins to match the new version number"
        - label: "Tag the release in GitHub with the new version number"
        - label: "Create new zips file for distribution (encapsulated, standard, unified)"
        - label: "Create a release in GitHub with release notes"
        - label: "Upload encapsulated and standard zip files to the repository's Releases section"
        - label: "Upload unified zip file to the ZenCart Plugin Database with matching release notes"
        - label: "Clear out, close, and rename \"Next Version\" milestone to match the new version number"
        - label: "Announce the new release on the ZenCart Forums and other relevant channels"